//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTable
    {
        public int id { get; set; }
        public string Task { get; set; }
        public bool Done { get; set; }
        public System.DateTime Deadline { get; set; }
    }
}
